### ISSUE TITLE
1.6 seems to have gotten rid of support for Non Hue Zigbee lights

### ISSUE THREAD

**Issue by Etrit1** [Kakifrucht/LightBeat#14]
I'm wondering if it's just a change with the Hue API and that you can't do anything with it but I figured I'd mention it.
Only my Hue lights are now showing within Lightbeat.

*almost cries*

IF you found a way to make it work still it would be amazing!   But, if not; I'll stick to 1.5.

Thanks for updating it! :-)

**Comment by Kakifrucht** [comment]
Yeah that is certainly not intended. What has changed is that LightBeat checks if the light has brightness control. Seems like your non Hue lights respond that they don't! This is to filter ZigBee switches and non light devices.

Since I definitely do want to support non Philips lights, there are a couple of options here. One is to do some more digging, maybe there is another way to discern lights from non lights via the API. The other is to add an overwrite to advanced settings that won't filter for cases like yours.

Can you do a manual API call to your bridge and send me the response? You do that by accessing your.bridge.ip/api/{username}/lights

The username is logged by LightBeat, if you used the installer simply run LightBeat_console.bat in your install folder and copy it from there. Thanks!

**Comment by Kakifrucht** [comment]
I believe I have found a way that is (more?) compatible with all sorts of ZigBee lights. I'll push a 1.6.1 release very soon to fix this!

**Comment by Kakifrucht** [comment]
Hopefully fixed in v1.6.1, please let me know if not.
